import = ["/Users/orhid/.config/alacritty/colours.toml", "/Users/orhid/.config/alacritty/fonts.toml"]

[bell.command]
args = ["/System/Library/Sounds/Pop.aiff"]
program = "afplay"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[scrolling]
auto_scroll = false
faux_multiplier = 0
history = 7776
multiplier = 3

[shell]
args = ["attach"]
program = "/opt/homebrew/bin/tmux"

[window]
dynamic_title = true
live_config_reload = true
save_to_clipboard = true
title = "alacritty"

[window.dimensions]
columns = 84
lines = 24

[window.padding]
x = 12
y = 12
