import = ["/Users/bartoszfurmanek/.config/alacritty/colours.toml", "/Users/bartoszfurmanek/.config/alacritty/fonts.toml"]

[bell.command]
args = ["/System/Library/Sounds/Pop.aiff"]
program = "afplay"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[shell]
args = ["attach"]
program = "/opt/homebrew/bin/tmux"

[window]
dynamic_title = true
title = "alacritty"

decorations = "Buttonless"
opacity = 0.9
blur = true

option_as_alt = "OnlyRight"

[window.dimensions]
columns = 84
lines = 24

[window.padding]
x = 12
y = 12
