[cursor]
blink_interval = 576
blink_timeout = 0
vi_mode_style = {shape = "Block", blinking = "Off"}

[cursor.style]
shape = "Block"
blinking = "On"

[font]
# ligatures = true
size = 14

[font.normal]
family = "Hasklug Nerd Font Mono"
style = "Regular"


[font.bold]
family = "Hasklug Nerd Font Mono"
style = "Bold"

[font.italic]
family = "Hasklug Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "Hasklug Nerd Font Mono"
style = "Bold Italic"
