#!/bin/sh

HISTFILE="$HOME"/.config/zsh/history
HISTSIZE=1296
SAVEHIST=1296

export GPG_TTY=($tty)

export PATH=/usr/local/bin:$PATH
export PATH=/opt/homebrew/bin:$PATH
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$HOME/.cabal/bin:$PATH
export PATH=$HOME/.ghcup/bin:$PATH
export PATH=$HOME/.local/bin:$PATH
