#!/bin/sh

export MACOSX_DEPLOYMENT_TARGET="13.2" # necessary to make luaJIT work

HISTFILE="$HOME"/.config/zsh/history
HISTSIZE=279936
SAVEHIST=279936

export PATH=/usr/local/bin:$PATH
export PATH=/opt/homebrew/bin:$PATH
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$HOME/.cabal/bin:$PATH
export PATH=$HOME/.ghcup/bin:$PATH
